### PR TITLE
Migrates code to Swift 4.2 and adds recommended project settings.

### PR DESCRIPTION
**Pull request by StephanPartzsch**

### CODE REVIEW

**Comment by StephanPartzsch** [comment]
You need to increase the version of your pod accordingly.

**Comment by lemanhtien** [comment]
@StephanPartzsch Thanks for reminding me. I just updated pod version 💯

**Comment by StephanPartzsch** [comment]
Awesome, thank you :)

**Comment by StephanPartzsch** [comment]
Can you have a look at the PR and the merge? In the the repo in the master branch are no changes and there is no merge commit too. Something strange there...

**Comment by lemanhtien** [comment]
hmm may be I made a mistake to remove it.
I will revert Master branch to the old one, and can you create a merge request again?

Thank you

**Comment by StephanPartzsch** [comment]
NP. The new PR is there ;)

**Comment by lemanhtien** [comment]
💯

**Pull request merged**
